---
- name: Copy the startup-file to the remote machine
  hosts: all 
  tasks:
    - name: Copy startup
      copy:
        src: ./startup.sh  
        dest: /home/s-research/repos/
        mode: '0774'



- name: Copy the stopall-file to the remote machine
  hosts: all
  tasks:
    - name: Copy stopall
      copy:
        src: ./stopall.sh
        dest: /home/s-research/repos/
        mode: '0774'

# - name: Copy the setup_docker_network-file to the remote machine
#   hosts: all
#   tasks:
#     - name: Copy file
#       copy:
#         src: ./setup_docker_network.sh
#         dest: /home/s-research/repos/
#         mode: '0774'
