---
 - hosts: all
   tasks:
   - name: Creates an entry like "@reboot /home/s-research/repos/startup.sh"
     ansible.builtin.cron:
       name: "a job for reboot"
       special_time: reboot
       job: "su s-research -l -c  "cd /home/s-research/repos && ./startup.sh""
       user: root
     become: true
...
